import type { Metadata } from "next";
import { Fraunces, Hanken_Grotesk } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { MobileActionBar } from "@/components/MobileActionBar";
import { ScrollToTop } from "@/components/ScrollToTop";
import { LocalBusinessJsonLd } from "@/components/JsonLd";
import { business, SITE_URL } from "@/lib/business";

// Display — warm soft serif, moderate weights (restrained, not loud).
const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
  // Variable font — full weight range available; SOFT axis for the warmer cut.
  axes: ["SOFT"],
  display: "swap",
});

// Body / UI — high-readability humanist grotesk.
const hanken = Hanken_Grotesk({
  variable: "--font-hanken",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${business.name} — Catering & Deli in West Boylston, MA`,
    template: `%s · ${business.name}`,
  },
  description:
    "Full-service catering and a fresh made-to-order deli in West Boylston, MA. Corporate breakfasts & lunches, college team boxed lunches, BBQs, and our signature Breakfast Pizza. Get a catering quote.",
  keywords: [
    "catering West Boylston",
    "Worcester catering",
    "corporate catering",
    "boxed lunches",
    "breakfast pizza",
    "deli West Boylston MA",
  ],
  openGraph: {
    type: "website",
    siteName: business.name,
    title: `${business.name} — Catering that makes you look good`,
    description:
      "Full-service catering and a fresh deli serving the Greater Worcester area.",
    url: SITE_URL,
    // OG/Twitter images are generated by app/opengraph-image.tsx (file convention).
  },
  twitter: {
    card: "summary_large_image",
    title: `${business.name}`,
    description:
      "Full-service catering and a fresh deli serving the Greater Worcester area.",
  },
  alternates: { canonical: "/" },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${fraunces.variable} ${hanken.variable} h-full antialiased`}
    >
      {/* grain adds subtle paper atmosphere; pb on small screens reserves room
          for the persistent mobile action bar so it never overlaps content. */}
      <body className="grain flex min-h-full flex-col pb-20 lg:pb-0">
        <LocalBusinessJsonLd />
        <ScrollToTop />
        <Header />
        <main className="relative z-10 flex-1">{children}</main>
        <Footer />
        <MobileActionBar />
      </body>
    </html>
  );
}
